### PR TITLE
Review of DID Auth docs

### PR DESCRIPTION
**Pull request by miltonwg**

### CODE REVIEW

**Comment by miltonwg** [comment]
> "[[[The sdr MUST be sent in a signed JWT format — WHY?]]]"

is this sentence correct? in file **ssi/specs/did-auth.markdown**

**Comment by miltonwg** [comment]
Some comments for the sequential diagram **/assets/img/ssi/10_did_auth_sign_up.png**

1. Where it says `choose persona` shouldn't it be `choose persona + select wallet provider`?
2. When the `address` is returned, shouldn't it be `{address, did}`?

**Comment by miltonwg** [comment]
The subtitles below the section `How to send tokens` are all seen in smallest font size than the actual text.

**Comment by javiesses** [comment]
> The subtitles below the section `How to send tokens` are all seen in smallest font size than the actual text.

This is related to the chosen theme for the docs. Will change once it is published in the Dev Portal

**Comment by javiesses** [comment]
> Some comments for the sequential diagram **/assets/img/ssi/10_did_auth_sign_up.png**
> 
> 1. Where it says `choose persona` shouldn't it be `choose persona + select wallet provider`?
> 2. When the `address` is returned, shouldn't it be `{address, did}`?

1. I don't think the chosen wallet is related to the protocol. The protocol does not care on the way the user signs messages, it just need the proof that is in control of the private key
2. This protocol assumes the address is contained in the did. The service expects a did

**Comment by miltonwg** [comment]
> > Some comments for the sequential diagram **/assets/img/ssi/10_did_auth_sign_up.png**
> > 
> > 1. Where it says `choose persona` shouldn't it be `choose persona + select wallet provider`?
> > 2. When the `address` is returned, shouldn't it be `{address, did}`?
> 
>     1. I don't think the chosen wallet is related to the protocol. The protocol does not care on the way the user signs messages, it just need the proof that is in control of the private key
> 
>     2. This protocol assumes the address is contained in the did. The service expects a did

1. Ok!
2. So if the service expects a did, shouldn't the user return a did instead of an address?

**Review by ilanolkies — APPROVED** [review]

**Pull request merged**
